version: '2'
services:
  web:
    build: .
    mem_limit: 3g
    container_name: biostrips_web
    restart: always
    volumes:
      - .:/src
    ports:
      - "5001:5001"
    command: python main.py

