version: '2'
services:
  web:
    build: .
    mem_limit: 3g
    container_name: biostrips_test
    restart: always
    volumes:
      - .:/src
    ports:
      - "8080:8080"
    command: python main.py

